definitions:
  handlers.ConnectUserResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  handlers.CreateUserResponse:
    properties:
      code:
        type: integer
      id:
        type: integer
      message:
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  handlers.ImageInfoResponse:
    properties:
      created_at:
        type: string
      image_id:
        type: string
      link:
        type: string
      user_id:
        type: string
    type: object
  handlers.NewImageResponse:
    properties:
      code:
        type: integer
      id:
        type: string
      message:
        type: string
    type: object
  handlers.Response:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  handlers.UserInfoResponse:
    properties:
      code:
        type: integer
      data:
        properties:
          email:
            type: string
          name:
            type: string
          password:
            type: integer
        type: object
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /create-user:
    post:
      consumes:
      - application/json
      description: Create a new user with provided name, email, and password
      parameters:
      - description: User's pseudo
        in: formData
        name: pseudo
        required: true
        type: string
      - description: User's email
        in: formData
        name: email
        required: true
        type: string
      - description: User's password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully created user
          schema:
            $ref: '#/definitions/handlers.CreateUserResponse'
        "400":
          description: Missing fields
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a new user
      tags:
      - users
  /delete-image:
    delete:
      consumes:
      - application/json
      description: Delete an image by ID
      parameters:
      - description: Image ID to delete
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image deleted
          schema:
            $ref: '#/definitions/handlers.Response'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Delete an image
      tags:
      - images
  /info-image:
    get:
      consumes:
      - application/json
      description: Get information about images by user ID
      parameters:
      - description: User ID to retrieve image information
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image information
          schema:
            items:
              $ref: '#/definitions/handlers.ImageInfoResponse'
            type: array
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: No data found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get image information
      tags:
      - images
  /info-user:
    get:
      consumes:
      - application/json
      description: Get information about a user by ID
      parameters:
      - description: User ID to retrieve information
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User information
          schema:
            $ref: '#/definitions/handlers.UserInfoResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get user information
      tags:
      - users
  /new-image:
    post:
      consumes:
      - multipart/form-data
      description: Create a new image with provided file
      parameters:
      - description: Image file
        in: formData
        name: file
        required: true
        type: file
      - description: Image link
        in: formData
        name: link
        required: true
        type: string
      - description: User ID
        in: formData
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Image added successfully
          schema:
            $ref: '#/definitions/handlers.NewImageResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a new image
      tags:
      - images
  /users/connect:
    post:
      consumes:
      - application/json
      description: Authenticate user with provided email and password
      parameters:
      - description: User's email
        in: formData
        name: email
        required: true
        type: string
      - description: User's password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully authenticated
          schema:
            $ref: '#/definitions/handlers.ConnectUserResponse'
        "400":
          description: Missing fields
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Authenticate user
      tags:
      - users
swagger: "2.0"
